# @Home    : www.pi-apple.com
# @Author  : Leon
# @Email   : 88978827@qq.com
"""
Code Agent - Main orchestrator for API client generation
"""
import os
from typing import Optional
from .platform_doc_parser import PlatformDocParser
from .llm_remote import LLMRemote


class CodeAgent:
    """
    AI Agent that generates platform-specific API clients
    """

    def __init__(self):
        """Initialize the code agent with necessary services"""
        self.doc_parser = PlatformDocParser()
        self.llm = LLMRemote()

    def generate_api_client(
            self,
            platform: str,
            docs_url: str,
            mock_auth: bool = False,
            output_dir: str = 'src/generated_clients'
    ) -> str:
        """
        Generate a complete API client for the specified platform

        Args:
            platform: Platform name (e.g., 'snapchat', 'pinterest')
            docs_url: URL to API documentation
            mock_auth: If True, generate mock client; if False, generate production client
            output_dir: Directory to save generated code

        Returns:
            Path to generated file
        """
        print(f"\n{'=' * 60}")
        print(f"Step 1: Parsing API documentation")
        print(f"{'=' * 60}")

        # Parse API documentation
        api_info = self.doc_parser.get_api_info(docs_url, platform)

        print(f"\n{'=' * 60}")
        print(f"Step 2: Generating Python code with LLM")
        print(f"{'=' * 60}")

        # Generate code using LLM
        code = self.llm.generate_api_client_code(
            platform=platform,
            api_info=api_info,
            mock_auth=mock_auth
        )

        print(f"\n{'=' * 60}")
        print(f"Step 3: Saving generated code")
        print(f"{'=' * 60}")

        # Save to file
        output_file = self._save_code(code, platform, output_dir)

        # Add __init__.py if needed
        self._ensure_init_file(output_dir)

        print(f"✓ Code saved to: {output_file}")
        print(f"✓ Generated {len(code.split('def ')) - 1} functions")

        return output_file

    def _save_code(self, code: str, platform: str, output_dir: str) -> str:
        """
        Save generated code to file

        Args:
            code: Python code to save
            platform: Platform name
            output_dir: Output directory

        Returns:
            Path to saved file
        """
        # Ensure output directory exists
        os.makedirs(output_dir, exist_ok=True)

        # Generate filename
        filename = f"{platform}_api.py"
        filepath = os.path.join(output_dir, filename)

        # Add header comment
        header = f'''"""
{platform.upper()} Advertising API Client
Auto-generated by AI Ads Generator
Platform: {platform}
"""

'''

        # Write to file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(header + code)

        return filepath

    def _ensure_init_file(self, output_dir: str):
        """Create __init__.py in output directory if it doesn't exist"""
        init_file = os.path.join(output_dir, '__init__.py')
        if not os.path.exists(init_file):
            with open(init_file, 'w') as f:
                f.write('"""Generated API clients"""\n')
